/** Shared Plan2Agent toolkit file manifest. */

export const REPO_ONLY_SCRIPT_FILES = [
  'p2a_doctor.mjs',
  'p2a_handoff.mjs',
  'p2a_handoff_portability.mjs',
  'p2a_upgrade.mjs',
  'sync_cli_assets.mjs',
  'check_cli_parity.mjs',
  'run_fixtures.mjs',
  'p2a_tool_manifest.mjs',
];

export const PROJECT_RUNTIME_SCRIPT_FILES = [
  'p2a.mjs',
  'p2a_decision_ledger.mjs',
  'p2a_decisions.mjs',
  'p2a_shape.mjs',
  'p2a_paths.mjs',
  'p2a_constants.mjs',
  'p2a_project_config.mjs',
  'p2a_run_commands.mjs',
  'p2a_iteration.mjs',
  'p2a_tasks.mjs',
  'p2a_runs.mjs',
  'p2a_execute.mjs',
  'p2a_monitor_gate.mjs',
  'p2a_visual_review_gate.mjs',
  'p2a_acceptance_review_gate.mjs',
  'p2a_visual_media.mjs',
  'p2a_proposals.mjs',
  'p2a_eval.mjs',
  'p2a_memory.mjs',
  'p2a_radar_preflight.mjs',
  'p2a_run_paths.mjs',
  'p2a_run_store.mjs',
  'p2a_iteration_state.mjs',
  'p2a_spec_model.mjs',
  'validate_artifacts.mjs',
];

export const PROJECT_RUNTIME_SCHEMA_FILES = [
  'next.schema.json',
  'constitution.schema.json',
  'decisions.schema.json',
  'intake.schema.json',
  'spec.schema.json',
  'task-graph.schema.json',
  'task-context.schema.json',
  'review.schema.json',
  'run.schema.json',
  'run-index.schema.json',
  'visual-experience.schema.json',
  'visual-prototype.schema.json',
  'visual-review.schema.json',
  'acceptance-review.schema.json',
  'milestone-review.schema.json',
  'skill-proposal.schema.json',
  'proposal-review.schema.json',
  'proposal-curation.schema.json',
  'proposal-patch-draft.schema.json',
  'proposal-draft-approval.schema.json',
  'eval-index.schema.json',
  'eval-digest.schema.json',
  'eval-maintenance-draft.schema.json',
  'eval-maintenance-apply-report.schema.json',
];
